name: {{ cookiecutter.conda_environment }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python={{cookiecutter.python_version}}
  - jupyterlab                      # necessary to run notebooks
  - pandoc =2.7                     # necessary to compile the paper
  - pandoc-crossref                 # necessary to compile the paper
  - pip
  - pip:
    - pandoc-include                 # necessary to compile the paper
    - pandoc-latex-admonition        # necessary to compile the paper
    - watermark                      # add metadata to notebooks
